---
local_saca_saei_xx_path: "/home/work/deploy-packages/saeServers_V2/WIN_SACA_SAEI/{{ version }}"
local_op_zipfilepath: "{{ local_saca_saei_xx_path }}/op.zip"
remote_package_path: "D:\\ansible_workspace\\WIN_SACA_SAEI\\{{ version }}"
remote_sae_path: "D:\\production\\V2\\saeServers"
configfilepath_saca: "{{ remote_sae_path }}\\saca\\config.py"
configfilepath_saei: "{{ remote_sae_path }}\\saei\\config.py"

delete_all_scheduled_tasks: False
config_all_scheduled_tasks: False

