# deploy saca_saei{0|1|2}.tar.gz

---
#- name: set current datetime var fact
#  set_fact: 
#    online_datetime: "{{lookup('pipe','date +%Y%m%d-%H%M%S')}}"
#    delegate_to: 127.0.0.1

- name: set remote ansible online path var fact
  set_fact: 
    remote_ansible_online_path: "D:\\ansible_online\\WIN_SACA_SAEI\\{{ version }}"
    delegate_to: 127.0.0.1

- name: check remote ansible online path exist
  win_file: path={{ remote_ansible_online_path }} state=directory

- name: check remote sae path exist
  win_file: path={{ remote_sae_path }} state=directory

- name: check remote package path exist
  win_file: path={{ remote_package_path }} state=directory

# Windows 拷贝目录需要后缀 '\'
- name: copy op.tar.gz to online path
  win_copy:
    src: "{{ local_op_zipfilepath }}"
    dest: "{{ remote_ansible_online_path }}\\"
    remote_src: no
  register: copy_op_zip_result

- name: unzip op scripts
  win_unzip: 
    src: "{{ remote_ansible_online_path }}\\op.zip"
    dest: "{{ remote_ansible_online_path }}"
  when: not ansible_check_mode and copy_op_zip_result.changed
    
# Windows 拷贝目录需要后缀 '\'
- name: copy tca.tar.gz to online path
  win_copy:
    src: "{{ local_tca_zipfilepath }}"
    dest: "{{ remote_package_path }}\\"
    remote_src: no
  register: copy_tca_zip_result

#- debug: var=copy_op_zip_result
#
## lookup datetime 必须在这里定义, 在 vars 中会导致每次使用都是不一样的值
########################################################################################

