# deploy ts_cc_scripts.tar.gz 
#

---
- name: set current datetime var fact
  set_fact: 
    online_datetime: "{{lookup('pipe','date +%Y%m%d-%H%M%S')}}"
    delegate_to: 127.0.0.1

- name: set run path var fact
  set_fact: 
    online_runpath: "/home/work/.online/TS_CC_SCRIPTS/{{ online_datetime }}"
    delegate_to: 127.0.0.1

- name: create remote online directory
  file: path={{ online_runpath }} state=directory

- name: copy and untar op scripts to remote online directory
  unarchive: 
    src: "{{ src_op_tar_gz }}"
    dest: "{{ online_runpath }}"
    extra_opts: [--strip-components=1]
  when: not ansible_check_mode

#
## lookup datetime 必须在这里定义, 在 vars 中会导致每次使用都是不一样的值
########################################################################################

- name: create remote package directories
  file: path={{ online_packagepath }} state=directory

- name: copy ts_cc_scripts.tar.gz package to the ansible workspace
  copy:
    src: "{{ src_ts_cc_scripts_tar_gz }}"
    dest: "{{ online_packagepath }}"
    backup: yes

- name: start online ts cc scripts scripts
  shell: "source /home/work/.bash_profile && /bin/bash {{ online_runpath }}/ts_cc_scripts_online.sh {{ ts_cc_scripts_version }} >> {{ ts_cc_scripts_version }}"
  args:
    chdir: "{{ online_runpath }}"
    creates: "{{ ts_cc_scripts_version }}"

- name: add sync apps crontab task
  cron:
    name: "sync apps"
    job: "/home/work/tools/python2.7.13/bin/python /home/work/production/V2/saeServers/timescripts/sync_apps/sync_apps.py >/dev/null 2>&1"
    minute: "*/3"
    backup: yes

- name: add app status report crontab task
  cron:
    name: "app status report"
    job: "/home/work/tools/python2.7.13/bin/python /home/work/production/V2/saeServers/timescripts/app_status_report/appstatus_report.py >/dev/null 2>&1"
    minute: "*/3"
    backup: yes

