# deploy sgw module

---
#- name: set current datetime var fact
#  set_fact: 
#    online_datetime: "{{lookup('pipe','date +%Y%m%d-%H%M%S')}}"
#  delegate_to: 127.0.0.1

- name: check remote op path exist
  file: path={{ remote_op_path }} state=directory

- name: check remote code path exist
  file: path={{ remote_code_path }} state=directory

##################################################################

- name: copy and unarchive op.tgz to remote op path
  unarchive: 
    src: "{{ local_op_tgz_filepath }}"
    dest: "{{ remote_op_path }}"
    extra_opts: [--strip-components=1]
  when: not ansible_check_mode

##################################################################

- name: copy sgw_module.tgz code package to remote code path
  copy:
    src: "{{ local_code_tgz_filepath }}"
    dest: "{{ remote_code_path }}"

- name: start online sgw module
  shell: "source /home/work/.bash_profile && /bin/bash {{ remote_op_path }}/sgw_module_online.sh {{ version }} {{ ENV }} >> online.log"
  args:
    chdir: "{{ remote_op_path }}"
    creates: "online.log"

