# deploy backup log script
#
---
- name: check remote directory exist
  file: path={{remote_sae_path}} state=directory

- name: copy and untar ts backup log scripts to remote directory
  unarchive:
    src: "{{ local_ts_backup_log_tar_gz_filepath }}"
    dest: "{{ remote_sae_path }}"
  when: not ansible_check_mode

- name: change config.py WHERE value to 2
  lineinfile: 
    dest: "{{remote_sae_path}}/timescripts/backup_log_saei/config.py"
    regexp: "^WHERE = "
    line: "WHERE = 2"

- name: add backup log crontab task
  cron:
    name: "backup log"
    job: "/home/work/tools/python2.7.13/bin/python /home/work/production/V2/saeServers/timescripts/backup_log_saei/backup_log.py >/dev/null 2>&1"
    minute: 10
    hour: 3
    weekday: 3,6
    backup: yes

