# deploy backup log script

---

- name: check remote directory exist
  file: path={{remote_sae_path}} state=directory

- name: copy and untar ts backup log scripts to remote directory
  unarchive:
    src: "{{ src_ts_backup_log_tar_gz }}"
    dest: "{{ remote_sae_path }}"
    extra_opts: [--strip-components=1]
  when: not ansible_check_mode

- name: start online backup log script
  shell: "sed -i 's/WHERE = 0/WHERE = 2/g' timescripts/backup_log_saei/config.py"
  args:
    chdir: "{{remote_sae_path}}"

- name: add backup log crontab task
  cron:
    name: "backup log"
    job: "/home/work/tools/python2.7.13/bin/python /home/work/production/V2/saeServers/timescripts/backup_log_saei/backup_log.py >/dev/null 2>&1"
    minute: 10
    hour: 3
    weekday: 3,6
    backup: yes

