# deploy timescripts.tar.gz

---
- name: check remote op path exist
  win_file: path={{ remote_op_path }} state=directory

- name: check remote code path exist
  win_file: path={{ remote_code_path }} state=directory

- name: check remote sae path exist
  win_file: path={{ remote_sae_path }} state=directory

##################################################################

# Windows 拷贝到目录需要后缀 '\'
- name: copy op.zip to remote op path
  win_copy:
    src: "{{ local_op_zip_filepath }}"
    dest: "{{ remote_op_path  }}\\"
    remote_src: no
  register: copy_op_zip_result

# copy 成功且 changed is True
- name: unzip op.zip to remote op path
  win_unzip: 
    src: "{{ remote_op_path }}\\op.zip"
    dest: "{{ remote_op_path }}"
  when: not ansible_check_mode and copy_op_zip_result.changed

##################################################################
    
# Windows 拷贝到目录需要后缀 '\'
- name: copy ts_ca_scripts.zip to remote code path
  win_copy:
    src: "{{ local_code_zip_filepath }}"
    dest: "{{ remote_code_path }}\\"
    remote_src: no
  register: copy_ts_ca_scripts_zip_result

- name: unzip ts_ca_scripts.zip to remote sae path
  win_unzip: 
    src: "{{ remote_code_path }}\\ts_ca_scripts.zip"
    dest: "{{ remote_sae_path }}"
  when: not ansible_check_mode

- name: change config 
  win_lineinfile:
    path: "{{ item }}"
    regexp: "^WHERE = "
    line: "WHERE = 2"
  with_items:
    - "{{ configfilepath_backup_log_saei }}"
    - "{{ configfilepath_restart_saei }}"

- name: delete all scheduled tasks
  win_shell: "{{ remote_op_path }}\\ascripts_op\\WinDeleteAllScheduledTasksForTcaOrSaca.ps1 >> online.log"
  args:
    chdir: "{{ remote_op_path }}"
  when: delete_all_scheduled_tasks is defined and delete_all_scheduled_tasks == True

- name: config all scheduled tasks
  win_shell: "{{ remote_op_path }}\\ascripts_op\\WinConfigScheduledTasksForTcaOrSaca.ps1 -HostName {{ inventory_hostname }} >> online.log"
  args:
    chdir: "{{ remote_op_path }}"
  when: config_all_scheduled_tasks is defined and config_all_scheduled_tasks == True

#- name: debug var
#  debug: var=config_backup_log_saei_file_path

######################################################################
#               Windows server 2008 not support win_scheduled task
## Create a scheduled task to backup log
#- name: Create a schedule task to backup log
#  win_scheduled_task:
#    name: '日志备份'
#    description: '用来备份运行日志'
#    executable: D:\production\V2\saeServers\timescripts\backup_log_saei\start_backup_log.bat
#    enabled: yes
#    frequency: weekly
#    days_of_week: 2,6
#    time: 03:10am
#    path: \backup_log
#    state: present
#    user: System
#    runlevel: highest
#  tags:
#    - scheduled
#
