# deploy sgw.tar.gz for test env

---
#- name: set current datetime var fact
#  set_fact: 
#    online_datetime: "{{lookup('pipe','date +%Y%m%d-%H%M%S')}}"
#  delegate_to: 127.0.0.1

- name: set remote ansible online path var fact
  set_fact: 
    remote_ansible_online_path: "/home/work/.ansible_online/SGW/{{ version }}"
  delegate_to: 127.0.0.1

- name: check remote ansible online path exist
  file: path={{ remote_ansible_online_path }} state=directory

- name: copy and untar op scripts to remote ansible online path
  unarchive: 
    src: "{{ local_op_tar_gz_filepath }}"
    dest: "{{ remote_ansible_online_path }}"
    extra_opts: [--strip-components=1]
  when: not ansible_check_mode

#
# lookup datetime 必须在这里定义, 在 vars 中会导致每次使用都是不一样的值
#######################################################################################


- name: check remote package path exist
  file: path={{ remote_package_path }} state=directory

- name: copy sgw.tar.gz package to remote package path
  copy:
    src: "{{ local_sgw_tar_gz_filepath }}"
    dest: "{{ remote_package_path }}"
    backup: yes

- name: start online sgw module
  shell: "source /home/work/.bash_profile && /bin/bash {{ remote_ansible_online_path }}/sgw_module_online_20.sh {{ version }} >> {{ version }}"
  args:
    chdir: "{{ remote_ansible_online_path }}"
    creates: "{{ version }}"

