# deploy ts_cc_scripts.tar.gz 
#

---
- name: set current datetime var fact
  set_fact: 
    online_datetime: "{{lookup('pipe','date +%Y%m%d-%H%M%S')}}"
    delegate_to: 127.0.0.1

- name: set remote ansible online path var fact
  set_fact: 
    remote_ansible_online_path: "/home/work/.ansible_online/TS_CC_SCRIPTS/{{ online_datetime }}"
    delegate_to: 127.0.0.1

- name: check remote ansible online exist
  file: path={{ remote_ansible_online_path }} state=directory

- name: copy and untar op scripts to remote ansible online exist
  unarchive: 
    src: "{{ local_op_tar_gz_filepath }}"
    dest: "{{ remote_ansible_online_path }}"
    extra_opts: [--strip-components=1]
  when: not ansible_check_mode

#
## lookup datetime 必须在这里定义, 在 vars 中会导致每次使用都是不一样的值
########################################################################################

- name: check remote ansible workspace path exist
  file: path={{ remote_ansible_workspace_path }} state=directory

- name: copy ts_cc_scripts.tar.gz package to remote ansible workspace path
  copy:
    src: "{{ local_ts_cc_scripts_tar_gz_filepath }}"
    dest: "{{ remote_ansible_workspace_path }}"
    backup: yes

- name: start online ts cc scripts scripts
  shell: "source /home/work/.bash_profile && /bin/bash {{ remote_ansible_online_path }}/ts_cc_scripts_online.sh {{ version }} >> {{ version }}"
  args:
    chdir: "{{ remote_ansible_online_path }}"
    creates: "{{ version }}"

- name: add sync apps crontab task
  cron:
    name: "sync apps"
    job: "/home/work/tools/python2.7.13/bin/python /home/work/production/V2/saeServers/timescripts/sync_apps/sync_apps.py >/dev/null 2>&1"
    minute: "*/3"

- name: add app status report crontab task
  cron:
    name: "app status report"
    job: "/home/work/tools/python2.7.13/bin/python /home/work/production/V2/saeServers/timescripts/app_status_report/appstatus_report.py >/dev/null 2>&1"
    minute: "*/3"
