
#

- name: add backup log crontab task
  cron:
    name: "backup log"
    job: "/home/work/tools/python2.7.13/bin/python /home/work/production/V2/saeServers/timescripts/backup_log_saei/backup_log.py >/dev/null 2>&1"
    minute: 10
    hour: 3
    weekday: 3,6
    backup: yes

