# deploy timescripts.tar.gz

---
#- name: set the host type SACA or TCA
#  set_fact:
#    the_host_type: "{{ 'TCA' if inventory_hostname | upper | match('TCA-.*') else 'SACA' }}"
#  tags: 
#    - scheduled

- name: check remote package path exist
  win_file: 
    path: "{{ remote_package_path }}"
    state: directory
  tags:
    - code

- name: check remote sae path exist
  win_file: 
    path: "{{ remote_sae_path }}"
    state: directory
  tags:
    - code

# Windows 拷贝目录需要后缀 '\'
- name: copy timescripts.tar.gz to remote package path
  win_copy: 
    src: "{{ local_timescripts_zipfilepath }}"
    dest: "{{ remote_package_path }}\\"
    remote_src: no
  tags:
    - code

- name: unzip timescripts.tar.gz to remote sae path
  win_unzip: 
    src: "{{ remote_package_filepath }}"
    dest: "{{ remote_sae_path }}"
  when: not ansible_check_mode
  tags:
    - code

- name: change config 
  win_lineinfile:
    path: "{{ item }}"
    regexp: "^WHERE = "
    line: "WHERE = 2"
  with_items:
    - "{{ configfilepath_backup_log_saei }}"
    - "{{ configfilepath_restart_saei }}"
  tags:
    - code

#- name: debug var
#  debug: var=config_backup_log_saei_file_path

######################################################################
#               Windows server 2008 not support win_scheduled task
## Create a scheduled task to backup log
#- name: Create a schedule task to backup log
#  win_scheduled_task:
#    name: '日志备份'
#    description: '用来备份运行日志'
#    executable: D:\production\V2\saeServers\timescripts\backup_log_saei\start_backup_log.bat
#    enabled: yes
#    frequency: weekly
#    days_of_week: 2,6
#    time: 03:10am
#    path: \backup_log
#    state: present
#    user: System
#    runlevel: highest
#  tags:
#    - scheduled
#
## Create a scheduled task to backup saeirun
#
## Create a scheduled task to loop run restart saei
#


